[build-system]
requires = ["setuptools>=77.0", "setuptools-rust>=1.10", "Cython>=0.29.33"]
build-backend = "setuptools.build_meta"

[project]
name = "FastWARC"
version = "1.0.2"
description = "A high-performance WARC parsing library written in Rust with bindings for Python."
authors = [
    { name = "Janek Bevendorff" }
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "brotli",
    "click",
    "tqdm"
]

[project.urls]
repository = "https://github.com/chatnoir-eu/chatnoir-resiliparse"
homepage = "https://resiliparse.chatnoir.eu"
documentation = "https://resiliparse.chatnoir.eu"

[project.optional-dependencies]
all = [
    "fastwarc[fsspec]"
]
fsspec = [
    "fsspec",
    "s3fs",
]
test = [
    "fastwarc[all]",
    "pytest>=7.2.2",
    "pytest-cov>=4.0.0",
]

[project.scripts]
fastwarc = "fastwarc.cli:main"

[tool.setuptools.packages.find]
include = ["fastwarc", "fastwarc.legacy"]

[tool.setuptools.package-data]
"*" = ["*.pyi"]

[tool.cibuildwheel]
archs = "native"
build = "cp3*"
build-frontend = "build"
test-extras = ["all", "test"]

[tool.mypy]
exclude = ["fastwarc/cli\\.py", "fastwarc/legacy/.*"]

[[tool.mypy.overrides]]
module = ["fsspec.*"]
ignore_missing_imports = true
