coverage:
  range: 70..90
  round: down
  precision: 2
  status:
    project:
      default:
        threshold: 1%
  ignore:
    - "**/*_test.rs"
    - "**/tests/**"
    - "fastwarc-py/fastwarc/legacy/**"
parsers:
  lcov:
    partials_as_hits: true
comment:
  require_changes: true
