[package]
name = "fastwarc"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true
documentation.workspace = true
description = "A high-performance WARC parsing library for Python written in C++/Cython."
readme = "README.md"
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
data-encoding = "2.10"
uuid = { version = "1.18", features = ["v4"] }
encoding = "0.2"
lz4_flex = { version = "0.13", default-features = false, features = ["frame"] }
md-5 = "0.11"
sha1 = "0.11"
sha2 = "0.11"
time = { version = "0.3", features = ["formatting"] }
zlib-rs = "0.6"

[dev-dependencies]
pretty_assertions.workspace = true
