[package]
name = "fastwarc"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true
documentation.workspace = true
description = "A high-performance WARC parsing library written in Rust with bindings for Python."
readme = "README.md"
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
brotli = "8.0"
data-encoding = "2.10"
uuid = { version = "1.18", features = ["v4"] }
encoding = "0.2"
lz4_flex = { version = "0.13", default-features = false, features = ["frame"] }
md-5 = "0.11"
sha1 = "0.11"
sha2 = "0.11"
time.workspace = true
zlib-rs = "0.6"
zstd = { version = "0.13", features = ["zstdmt"] }
digest = "0.11"

[dev-dependencies]
pretty_assertions.workspace = true
