[package]
name = "fastwarc-py"
edition.workspace = true
publish = false

[lib]
name = "fastwarc"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
fastwarc = { path = "../../fastwarc-rs" }
pyo3 = { workspace = true, features = ["extension-module"] }
time.workspace = true

[build-dependencies]
pyo3-build-config.workspace = true
