# Copyright 2026 Janek Bevendorff
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from datetime import datetime
from enum import IntFlag
from os import PathLike
from typing import BinaryIO, Callable, Dict, Iterable, Iterator, Literal, Optional, Self, Tuple, Union

from .stream_io import _GenericReader, _GenericWriter, WarcReader, WarcWriter


class WarcRecordType(IntFlag):
    warcinfo = 2
    response = 4
    resource = 8
    request = 16
    metadata = 32
    revisit = 64
    conversion = 128
    continuation = 256
    unknown = 512
    any_type = 65535
    no_type = 0

    def __int__(self) -> int: ...

    def __index__(self) -> int: ...

    def __and__(self, other: int) -> int: ...

    def __rand__(self, other: int) -> int: ...

    def __or__(self, other: int) -> int: ...

    def __ror__(self, other: int) -> int: ...

    def __xor__(self, other: int) -> int: ...

    def __rxor__(self, other: int) -> int: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...


warcinfo = WarcRecordType.warcinfo
response = WarcRecordType.response
resource = WarcRecordType.resource
request = WarcRecordType.request
metadata = WarcRecordType.metadata
revisit = WarcRecordType.revisit
conversion = WarcRecordType.conversion
continuation = WarcRecordType.continuation
unknown = WarcRecordType.unknown
no_type = WarcRecordType.no_type
any_type = WarcRecordType.any_type


class HeaderMap:
    def __new__(cls, encoding: str = "utf-8") -> Self: ...

    @property
    def reason_phrase(self) -> Optional[str]: ...

    @property
    def status_code(self) -> Optional[int]: ...

    @property
    def status_line(self) -> Optional[str]: ...

    @status_line.setter
    def status_line(self, status_line: str): ...

    @property
    def status_line_bytes(self) -> Optional[bytes]: ...

    @status_line_bytes.setter
    def status_line_bytes(self, status_line: bytes): ...

    def encoding(self) -> str: ...

    def parse(self, reader: Union[WarcReader, BinaryIO, _GenericReader], has_status_line: bool = True) -> int: ...

    def write(self, writer: Union[WarcWriter, BinaryIO, _GenericWriter]) -> int: ...

    def append(self, key: str, value: str): ...

    def to_dict(self) -> Dict[str, str]: ...

    # deprecated
    def asdict(self) -> Dict[str, str]: ...

    def to_tuples(self) -> Tuple[Tuple[str, str], ...]: ...

    # deprecated
    def astuples(self) -> Tuple[Tuple[str, str], ...]: ...

    def is_empty(self) -> bool: ...

    def clear(self): ...

    def get(self, key: str, default: Optional[str] = None) -> Optional[str]: ...

    def get_multiple(self, key: str) -> Tuple[str, ...]: ...

    def get_bytes(self, key: bytes, default: Optional[bytes] = None) -> Optional[bytes]: ...

    def get_bytes_multiple(self, key: bytes) -> Tuple[bytes, ...]: ...

    def contains_key(self, key: str) -> bool: ...

    def contains_key_bytes(self, key: bytes) -> bool: ...

    def set(self, key: str, value: str): ...

    def set_bytes(self, key: bytes, value: bytes): ...

    def append_bytes(self, key: bytes, value: bytes): ...

    def remove(self, key: str): ...

    def remove_bytes(self, key: bytes): ...

    def items(self) -> Tuple[Tuple[str, str], ...]: ...

    def items_bytes(self) -> Tuple[Tuple[bytes, bytes], ...]: ...

    def keys(self) -> Tuple[str, ...]: ...

    def keys_bytes(self) -> Tuple[bytes, ...]: ...

    def values(self) -> Tuple[str, ...]: ...

    def values_bytes(self) -> Tuple[bytes, ...]: ...

    def __getitem__(self, item: str) -> str: ...

    def __iter__(self) -> Iterator[Tuple[str, str]]: ...

    def __len__(self) -> int: ...

    def __setitem__(self, key: str, value: str): ...

    def __contains__(self, item: str) -> bool: ...

    def __eq__(self, other: HeaderMap) -> bool: ...

    def __ne__(self, other: HeaderMap) -> bool: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __getnewargs__(self) -> Tuple[str]: ...

    def __getstate__(self) -> Tuple[bytes, bool]: ...

    def __setstate__(self, state: Tuple[bytes, bool]): ...


# Legacy name
WarcHeaderMap = HeaderMap


class WarcRecordPayloadReader(WarcReader):
    def readline(self, max_line_len: int = 8192) -> bytes: ...

    def consume(self, size: int = -1) -> int: ...


class WarcRecord:
    def __new__(cls) -> Self: ...

    @property
    def record_id(self) -> Optional[str]: ...

    @record_id.setter
    def record_id(self, record_id: str): ...

    @property
    def record_type(self) -> WarcRecordType: ...

    @record_type.setter
    def record_type(self, record_type: Union[WarcRecordType, int]): ...

    @property
    def content_length(self) -> int: ...

    @property
    def record_date(self) -> Optional[datetime]: ...

    @record_date.setter
    def record_date(self, record_date: datetime): ...

    @property
    def headers(self) -> HeaderMap: ...

    @property
    def is_http(self) -> bool: ...

    @is_http.setter
    def is_http(self, is_http: bool): ...

    @property
    def is_http_parsed(self) -> bool: ...

    @property
    def http_headers(self) -> Optional[HeaderMap]: ...

    @property
    def http_content_type(self) -> Optional[str]: ...

    @property
    def http_charset(self) -> Optional[str]: ...

    @property
    def http_date(self) -> Optional[datetime]: ...

    @property
    def http_last_modified(self) -> Optional[datetime]: ...

    @property
    def reader(self) -> Optional[WarcRecordPayloadReader]: ...

    @property
    def stream_pos(self) -> int: ...

    @property
    def is_frozen(self) -> bool: ...

    def init_headers(
            self, content_length: int = 0, record_type: WarcRecordType = no_type, record_urn: Optional[bytes] = None
    ): ...

    def freeze(self) -> bool: ...

    def set_bytes_content(self, content: bytes): ...

    def set_bytes_payload(self, content: bytes): ...

    def consume(self, n: Optional[int] = None) -> int: ...

    def parse_warc_headers(self, quirks_mode: bool = False) -> int: ...

    def parse_http(self, auto_decode: Literal['none', 'content', 'transfer', 'all'] = 'none'): ...

    def verify_block_digest(self, consume: bool = False) -> bool: ...

    def verify_payload_digest(self, consume: bool = False) -> bool: ...

    def write(
            self,
            stream: Union[WarcWriter, BinaryIO, _GenericWriter],
            checksum_data: bool = False,
            payload_digest: Optional[bytes] = None,
            chunk_size: int = 16384
    ) -> int: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __getnewargs__(self) -> Tuple[()]: ...

    def __getstate__(self) -> Tuple[bytes, bool]: ...

    def __setstate__(self, state: Tuple[bytes, bool]): ...


class ArchiveIterator(Iterable[WarcRecord]):
    def __new__(
            cls,
            stream: Union[WarcReader, BinaryIO, _GenericReader, PathLike, str],
            record_types: WarcRecordType = any_type,
            parse_http: bool = True,
            min_content_length: int = -1,
            max_content_length: int = -1,
            func_filter: Optional[Callable[[WarcRecord], bool]] = None,
            verify_digests: bool = False,
            quirks_mode: bool = False,
            auto_decode: Literal['none', 'content', 'transfer', 'all'] = 'none',
            stream_detect: bool = True,
            fsspec_args=None,
    ) -> Self: ...

    def __iter__(self) -> Iterator[WarcRecord]: ...

    def __next__(self) -> WarcRecord: ...


# ArchiveIterator filter predicates

def is_warc_10(record: WarcRecord) -> bool: ...


def is_warc_11(record: WarcRecord) -> bool: ...


def has_block_digest(record: WarcRecord) -> bool: ...


def has_valid_block_digest(record: WarcRecord) -> bool: ...


def has_payload_digest(record: WarcRecord) -> bool: ...


def has_valid_payload_digest(record: WarcRecord) -> bool: ...


def is_http(record: WarcRecord) -> bool: ...


def is_concurrent(record: WarcRecord) -> bool: ...
